#!/usr/bin/env python
# -*- coding: utf-8 -*-

# Each array of cutscene text contains an array for each
# line of text in that cutscene. Each line array is
# organized as follows: [text, is_narrator, time_to_wait_for_line_to_appear].
text = {

    "intro_cutscene" : [["KEITH IS GONE.", True, 0],
                        ["...", False, 1500],
                        ["What did you just say to me?", False, 1000],
                        ["THIS IS A LOVELY HOME YOU HAVE.", True, 1500],
                        ["THOSE ARE SOME BEAUTIFUL FLOWERS OUTSIDE.", True, 1500],
                        ["...um, thank you?", False, 1500],
                        ["YOU'RE VERY WELCOME.", True, 1500],
                        ["I don't think I understand what's happening.", False, 1500],
                        ["NOT HAPPENING: HAPPENED. AND I JUST TOLD YOU.", True, 1500],
                        ["Okay, but who are you?", False, 1500],
                        ["DOES THAT MATTER?", True, 1500],
                        ["You tell me! What are you doing in my house?", False, 1500],
                        ["I EXPLAINED THAT ALREADY.", True, 2000],
                        ["...", False, 1500],
                        ["KEITH IS-", True, 1000],
                        ["Gone, yes, I heard you the first time.", False, 1000],
                        ["THEN WHAT'S WRONG?", True, 1500],
                        ["For starters...", False, 1500],
                        ["Who's Keith?", False, 1000],
                        ["YOU KNOW WHO KEITH IS.", True, 1500],
                        ["...", False, 1500],
                        ["Look, I think maybe you have the wrong house.", False, 1000],
                        ["NO, I THINK NOT.", True, 2500],
                        ["YOURS IS THE ONLY HOUSE AROUND HERE WITH A TIME MACHINE.", True, 1500],
                        ["A what?", False, 2000],
                        ["A TIME MACHINE.", True, 1000],
                        ["THAT'S YOURS IN THE CORNER, ISN'T IT?", True, 1000],
                        ["Um...", False, 1500],
                        ["Well...", False, 1000],
                        ["You know, I suppose it is. Huh.", False, 1000],
                        ["THAT MAKES YOU THE ONLY ONE WHO CAN GO BACK FOR KEITH.", True, 1500],
                        ["But why would I go back for Keith?", False, 3000],
                        ["DO WE REALLY NEED TO GO OVER THAT AGAIN?", True, 1500],
                        ["...", False, 1500],
                        ["If I use this time machine, will you leave me alone?", False, 1500],
                        ["IF YOU'D LIKE.", True, 2000],
                        ["BUT YOU'RE NOT GOING BACK FOR ME.", True, 1500],
                        ["YOU'RE GOING BACK FOR-", True, 1500],
                        ["Keith, I get it already!", False, 1500],
                        ["IF YOU SAY SO.", True, 1500],
                        ["Fine, whatever. I'll do it.", False, 1500],
                        ["I HOPE YOU FIND WHAT YOU'RE LOOKING FOR.", True, 1500],
                        ["...", False, 2500],
                        ["You better be gone by the time I get back.", False, 1000],
                        ["Now, how do I turn this thing-", False, 1500],
                        ["Aaagghhhhh!!!", False, 1500],
                        ["(PRESS ANY KEY TO CONTINUE).", True, 2500]],
    "level1_cutscene" : [["Ooomph!", False, 0],
                         ["That was a bumpier ride than I expected.", False, 1000],
                         ["Hey, what gives!", False, 2000],
                         ["This is just my backyard!", False, 1500],
                         ["And where'd my time machine go?!", False, 1500],
                         ["IT SEEMS TO HAVE BROKEN UP WHEN YOU LANDED.", True, 2000],
                         ["You again?", False, 2000],
                         ["I'M JUST HERE TO HELP YOU THROUGH THIS.", True, 1500],
                         ["Fine. You can start by pointing me in Keith's direction.", False, 1500],
                         ["KEITH IS GONE.", True, 2000],
                         ["Gee, I think you might have mentioned that already.", False, 1500],
                         ["THE SHARDS OF YOUR MACHINE ARE AROUND HERE SOMEWHERE, THOUGH.", True, 2000],
                         ["YOU MIGHT WANT TO START BY LOOKING FOR THOSE.", True, 2500],
                         ["You know what?", False, 2000],
                         ["This is dumb.", False, 1500],
                         ["ONE MORE THING BEFORE YOU SET OFF, THOUGH:", True, 1500],
                         ["THIS PLACE MIGHT FEEL A LITTLE HAUNTED.", True, 2000],
                         ["...", False, 2000],
                         ["My backyard?", False, 1000],
                         ["TRY NOT TO LET YOUR SPIRITS OVERWHELM YOU.", True, 1500],
                         ["I changed my mind.", False, 1500],
                         ["This is really, really dumb.", False, 1500],
                         ["GOOD LUCK.", True, 2000],
                         ["YOU HAVE A LONG ROAD AHEAD OF YOU.", True, 1000],
                         ["(PRESS ANY KEY TO CONTINUE).", True, 2500]],
    "level2_cutscene" : [["There! I picked up all the pieces of your stupid time machine.", False, 0],
                         ["YOU MEAN YOUR TIME MACHINE.", True, 2000],
                         ["Whatever.", False, 1500],
                         ["Now what?", False, 1000],
                         ["WELL...", True, 1500],
                         ["NOW YOU USE IT.", True, 1000],
                         ["KEITH IS STILL GONE, AFTER ALL.", True, 1500],
                         ["Right. And apparently I'm his emergency contact.", False, 1500],
                         ["YOU'RE JUST THE ONLY ONE STILL TRYING TO REACH HIM.", True, 2000],
                         ["Yeah, well, I'm getting sick of it.", False, 2000],
                         ["Can we just get this over with?", False, 1500],
                         ["THERE'S NO RUSH.", True, 1500],
                         ["YOU CAN TAKE ALL THE TIME YOU NEED... REMEMBER?", True, 1000],
                         ["Yeah, sure. So where-", False, 2000],
                         ["I mean when-", False, 1500],
                         ["Am I going now?", False, 1500],
                         ["I'M AFRAID I COULDN'T TELL YOU.", True, 2000],
                         ["What do you mean you can't tell me?", False, 1500],
                         ["You're the whole reason I'm here!", False, 1500],
                         ["You've been telling me what to do this whole time!", False, 1500],
                         ["I'M SORRY YOU FEEL FRUSTRATED.", True, 1500],
                         ["I KNOW THIS ISN'T EASY.", True, 1500],
                         ["...", False, 1500],
                         ["You're a real piece of work, you know that?", False, 1000],
                         ["Aw, to hell with you.", False, 1500],
                         ["I'll figure this out on my-", False, 1500],
                         ["Aaagghhhhh!", False, 1500],
                         ["Ooomph.", False, 800],
                         ["I hate time travel.", False, 1500],
                         ["Now where am I supposed to be?", False, 1500],
                         ["Why's everything all red and dead?", False, 1500],
                         ["And where's my...", False, 1500],
                         ["...", False, 1500],
                         ["Oh, you've gotta be kidding me.", False, 1500],
                         ["Again?!", False, 1500],
                         ["What kind of dollar-store-grade time machine is this?!", False, 1000],
                         ["I swear to god, if I have to pick up all these pieces-", False, 2000],
                         ["YOU DON'T HAVE TO DO ANYTHING YOU DON'T WANT TO DO.", True, 2000],
                         ["You know what?", False, 2000],
                         ["I'm aware of that.", False, 1500],
                         ["And I don't know if you realize this...", False, 1500],
                         ["But your vague murmurings of support are about as helpful as a hole in my head.", False, 1500],
                         ["So if the next words out of your mouth aren't Keith's exact latitude and longitude...", False, 3000],
                         ["...then I'm not interested in hearing them.", False, 3000],
                         ["Got it?", False, 1500],
                         ["...", False, 1000],
                         ["Well?", False, 1000],
                         ["ALL I CAN OFFER IS MY SYMPATHY.", True, 2000],
                         ["Then you can go to hell.", False, 1500],
                         ["(PRESS ANY KEY TO CONTINUE).", True, 1500]],
    "level3_cutscene" : [["Is that it?", False, 0],
                         ["Is that all of them?", False, 1500],
                         ["Thank god.", False, 1500],
                         ["Please, PLEASE let that be the last time I have to do that.", False, 1000],
                         ["TRUST ME, IT ONLY GETS EASIER.", True, 2000],
                         ["Who asked you?", False, 1500],
                         ["I GET YOU'RE UPSET...", True, 1500],
                         ["BUT I'M HERE TO SUPPORT YOU.", True, 1500],
                         ["YOU KNOW THAT, RIGHT?", True, 1500],
                         ["...", False, 1500],
                         ["Just...", False, 1500],
                         ["Fine.", False, 1500],
                         ["What now, then?", False, 1500],
                         ["ONCE AGAIN, THAT'S UP TO YOU.", True, 1500],
                         ["YOU CAN KEEP ON SEARCHING FOR KEITH...", True, 1500],
                         ["OR YOU CAN STOP.", True, 2000],
                         ["Stop?", False, 1500],
                         ["What happened to your whole \"Keith is gone, oh no, go find Keith\" shtick?", False, 1500],
                         ["THE ONLY THING THAT'S HAPPENED, PERIOD:", True, 2500],
                         ["TIME.", True, 2000],
                         ["What, so now that's it?", False, 2000],
                         ["Now you're saying I should just give up?", False, 1500],
                         ["That this is taking too long?", False, 1500],
                         ["LIKE I SAID, THAT'S UP TO YOU.", True, 1500],
                         ["Well I'm not giving up now!", False, 1500],
                         ["Are you kidding me?", False, 1500],
                         ["After everything we've been through?", False, 1500],
                         ["I have to find Keith.", False, 1500],
                         ["You of all people should understand that.", False, 1500],
                         ["OF COURSE I UNDERSTAND.", True, 1500],
                         ["Well, good.", False, 1500],
                         ["AND WHEN YOU'RE READY, YOU WILL TOO.", True, 1500],
                         ["...", False, 1500],
                         ["Look, I'm going back now.", False, 1000],
                         ["Third time's the charm, right?", False, 1500],
                         ["Aaagghhhhhooomph.", False, 1500],
                         ["Ugh.", False, 1500],
                         ["I'm never gonna get used to that.", False, 1000],
                         ["...", False, 1500],
                         ["Hold on...", False, 1000],
                         ["Oh, no.", False, 1000],
                         ["Oh, no no no no no no no.", False, 1000],
                         ["No!", False, 1500],
                         ["Why!", False, 1000],
                         ["For the love of god, why?", False, 1000],
                         ["IT BROKE AGAIN, DIDN'T IT?", True, 1500],
                         ["Of course it broke again!", False, 1500],
                         ["You know it broke again!", False, 1500],
                         ["It's worse than that.", False, 1500],
                         ["I TAKE IT YOU'RE NOT HAPPY WITH WHERE YOU ENDED UP.", True, 1500],
                         ["Why did you bring me here?!", False, 2000],
                         ["What gives you the right?!", False, 1500],
                         ["I DIDN'T BRING YOU ANYWHERE.", True, 1500],
                         ["YOU KNOW THAT.", True, 1500],
                         ["I don't want to be here.", False, 1500],
                         ["YOU CAN'T ALWAYS TAKE CONTROL OF WHAT YOU REVISIT.", True, 1500],
                         ["THE PAST HAS A WAY OF PUSHING BACK.", True, 2000],
                         ["I can't do this.", False, 2000],
                         ["I can't handle seeing the market like this.", False, 1500],
                         ["It looks so...", False, 1500],
                         ["Normal.", False, 1500],
                         ["ISN'T THAT HOW YOU WANT TO BE SEEING IT?", True, 1500],
                         ["ISN'T THAT WHY YOU CAME BACK HERE?", True, 1500],
                         ["No!", False, 1500],
                         ["I don't want to be seeing it at all!", False, 1500],
                         ["I don't want to be here now-", False, 1500],
                         ["I didn't want to be here before-", False, 1500],
                         ["And I don't want to be here ever again!", False, 1500],
                         ["Please!", False, 1500],
                         ["I just want Keith back!", False, 1500],
                         ["I KNOW.", True, 1500],
                         ["BUT THAT MEANS COMING TO TERMS WITH WHAT HAPPENED HERE.", True, 1500],
                         ["I can't take this anymore.", False, 1500],
                         ["I really can't.", False, 1500],
                         ["Please.", False, 1500],
                         ["Help me.", False, 1000],
                         ["Please!", False, 1000],
                         ["Just tell me what I have to do, and I'll do it!", False, 1000],
                         ["I'M SORRY, BUT YOUR OPTIONS HAVEN'T CHANGED.", True, 1500],
                         ["Please...", False, 1500],
                         ["KEEP LOOKING...", True, 1000],
                         ["...OR DON'T.", True, 1500],
                         ["(PRESS ANY KEY TO CONTINUE).", True, 2500]],
    "level4_cutscene" : [["Okay.", False, 0],
                         ["Okay.", False, 1500],
                         ["We're back together again.", False, 1500],
                         ["THAT'S GOOD TO HEAR.", True, 1500],
                         ["And I can get away from this blasted marketplace.", False, 1500],
                         ["ARE YOU GOING TO KEEP GOING BACK?", True, 2000],
                         ["Yes.", False, 1500],
                         ["Like you said, he's gone.", False, 1000],
                         ["AND NOW YOU'VE SAID IT, TOO.", True, 1500],
                         ["YOU DON'T HAVE TO LIVE IN THE PAST TO MOVE FORWARD, YOU KNOW.", True, 1500],
                         ["That's not what this is!", False, 2000],
                         ["I just need to find him before... well...", False, 1500],
                         ["It's the least I can do.", False, 2000],
                         ["I owe him that much.", False, 1500],
                         ["I THINK YOU KNOW WHAT KEITH WOULD SAY TO THAT.", True, 1500],
                         ["Well, Keith's not here right now.", False, 2000],
                         ["I'll find him or die trying.", False, 1500],
                         ["I KNOW YOU SEE THE IRONY IN THAT.", True, 1500],
                         ["I KNOW YOU KNOW WHAT HE WANTS FROM YOU.", True, 1500],
                         ["...", False, 2000],
                         ["I just want him back.", False, 1500],
                         ["I KNOW.", True, 1500],
                         ["So are you gonna help me look, or not?", False, 1500],
                         ["I'LL BE HERE FOR YOU, WHATEVER YOU DECIDE.", True, 1500],
                         ["Thank you.", False, 2000],
                         ["Will my time machine break apart again?", False, 1500],
                         ["I GUESS SO.", True, 1500],
                         ["FOR NOW.", True, 1500],
                         ["SOMEDAY IT WON'T HURT AS MUCH TO GO BACK.", True, 1500],
                         ["Right.", False, 1500],
                         ["Okay.", False, 1500],
                         ["I guess in the meantime I'll keep picking up the pieces.", False, 1500],
                         ["AND I'LL HELP YOU HOWEVER I CAN.", True, 2000],
                         ["Sure.", False, 1500],
                         ["Time to go, then...", False, 1500],
                         ["...", False, 1500],
                         ["Huh.", False, 1500],
                         ["I barely felt it that time.", False, 1500],
                         ["I didn't feel it at all, actually.", False, 1500],
                         ["Where am I now?", False, 2000],
                         ["YOU TELL ME.", True, 1500],
                         ["Well it's weird, and blue, and cold, but...", False, 1500],
                         ["BUT?", True, 2000],
                         ["Nothing. It just... reminds me of someplace.", False, 1500],
                         ["But it's different.", False, 1500],
                         ["HOW SO?", True, 1500],
                         ["I don't know.", False, 1500],
                         ["It's just... off.", False, 1500],
                         ["Like a dream of somewhere you know really well.", False, 1500],
                         ["And it's not until you wake up that you realize how wrong it all was.", False, 2000],
                         ["AT LEAST YOU KNOW YOU'RE NOT DREAMING.", True, 2500],
                         ["I think I'd rather be.", False, 2000],
                         ["So what's the deal with my time machine?", False, 1500],
                         ["There's no way it broke after such a soft landing.", False, 1500],
                         ["I DON'T THINK IT DID.", True, 2000],
                         ["So where is it?", False, 1500],
                         ["WELL...", True, 1500],
                         ["Ah. Of course.", False, 1500],
                         ["Still scattered all around me.", False, 1500],
                         ["That's kind of weird, isn't it?", False, 1500],
                         ["WELL, IT'S NOT ALWAYS EASY TO KEEP THINGS TOGETHER.", True, 1500],
                         ["THESE THINGS TAKE TIME.", True, 2000],
                         ["Right.", False, 1500],
                         ["No wonder it feels like this is never gonna end.", False, 1500],
                         ["IT WILL.", True, 2000],
                         ["Sure.", False, 1500],
                         ["You know what the really weird thing is, though?", False, 1500],
                         ["I'm not sure I want it to.", False, 2500],
                         ["(PRESS ANY KEY TO CONTINUE).", True, 2500]],
    "level5_cutscene" : [["Well, here we are.", False, 0],
                         ["I finally realized what this place reminds me of.", False, 1500],
                         ["AND WHAT'S THAT?", True, 1500],
                         ["It's our backyard.", False, 1500],
                         ["In winter.", False, 1500],
                         ["WHY DID THAT SEEM SO STRANGE TO YOU?", True, 1500],
                         ["Keith and I just got the house in spring.", False, 1500],
                         ["We've never been here when there's snow.", False, 2000],
                         ["Why did the time machine bring me back before that?", False, 2000],
                         ["MAYBE IT DIDN'T BRING YOU BACK AT ALL.", True, 2000],
                         ["So this is... the future?", False, 2000],
                         ["Is this where I'll find Keith?", False, 1500],
                         ["THIS ISN'T THE FUTURE.", True, 1500],
                         ["...I don't understand.", False, 2000],
                         ["THERE'S NO SUCH THING AS TIME MACHINES, EITHER.", True, 1500],
                         ["YOU HAVEN'T LEFT THE PRESENT.", True, 2000],
                         ["No, that's not right.", False, 1500],
                         ["I was in our backyard before.", False, 1500],
                         ["It was in full bloom.", False, 1500],
                         ["Green as can be.", False, 1500],
                         ["LIKE IT LOOKED ON THE DAY OF THE ATTACK?", True, 1500],
                         ["Stop it.", False, 2000],
                         ["IT ISN'T SUMMER ANYMORE.", True, 1500],
                         ["I said stop!", False, 1500],
                         ["IT'S WINTER.", True, 1500],
                         ["HE'S BEEN GONE FOR MONTHS.", True, 1500],
                         ["No!", False, 1500],
                         ["YES.", True, 1000],
                         ["IT'S AWFUL, IT'S UNFAIR, BUT IT'S REAL.", True, 1500],
                         ["YOU CAN'T HIDE IN YOUR MEMORIES FOREVER.", True, 1500],
                         ["And why the hell not!", False, 1500],
                         ["Why should I want to be anywhere else?", False, 1500],
                         ["Innocent people don't die in my memories.", False, 1500],
                         ["YES, THEY DO.", True, 1500],
                         ["AND I KNOW YOU KNOW THAT.", True, 1500],
                         ["EVENTUALLY YOU HAVE TO ACCEPT IT.", True, 1500],
                         ["...", False, 2000],
                         ["I don't want him to be gone.", False, 1500],
                         ["I miss him so much.", False, 1500],
                         ["I KNOW.", True, 1500],
                         ["When does it stop hurting?", False, 2000],
                         ["MAYBE IT DOESN'T.", True, 1500],
                         ["AND MAYBE IT SHOULDN'T.", True, 1500],
                         ["BUT YOU CAN'T LET THE PAIN STOP YOU LIVING YOUR LIFE.", True, 1500],
                         ["How can I live knowing Keith died to save me?", False, 2000],
                         ["HOW CAN YOU NOT?", True, 2000],
                         ["IF YOU OWE HIM ANYTHING, SHOULDN'T IT BE A LONG, HAPPY LIFE?", True, 1500],
                         ["If anyone deserved that, it was Keith.", False, 2000],
                         ["Not me.", False, 1500],
                         ["THEN DO IT FOR KEITH.", True, 1500],
                         ["JUST BECAUSE HE'S GONE, DOESN'T MEAN HE ISN'T HERE.", True, 1500],
                         ["...", False, 2000],
                         ["We were gonna start a family.", False, 1500],
                         ["We were gonna turn the second bedroom into a nursery.", False, 1500],
                         ["I was gonna put in the crib I used as a baby, and he was gonna paint the ceiling with stars.", False, 2000],
                         ["Was that really too much to ask of the world?", False, 3000],
                         ["I TRULY WISH I COULD ANSWER THAT.", True, 2500],
                         ["...", False, 1500],
                         ["What do I do now?", False, 1500],
                         ["What is this not-time-machine I just put back together?", False, 1500],
                         ["TRY IT.", True, 1500],
                         ["SEE WHERE IT TAKES YOU.", True, 1500],
                         ["AND IF IT BREAKS AGAIN...", True, 1500],
                         ["YOU KNOW HOW TO DEAL.", True, 1500],
                         ["(PRESS ANY KEY TO CONTINUE).", True, 1500]]
}
