#!/usr/bin/env python
# -*- coding: utf-8 -*-

# Each array of cutscene text contains an array for each
# line of text in that cutscene. Each line array is
# organized as follows: [text, is_narrator, time_to_wait_for_line_to_appear].
text = {

    "intro_cutscene" : [["KEITH IS GONE.", True, 0],
                        ["...", False, 1500],
                        ["What did you say to me?", False, 1000],
                        ["THIS IS A LOVELY HOME YOU HAVE.", True, 1500],
                        ["...um, thank you?", False, 1500],
                        ["YOU'RE QUITE WELCOME.", True, 1500],
                        ["I don't understand what's happening.", False, 1500],
                        ["I JUST TOLD YOU WHAT'S HAPPENING.", True, 1500],
                        ["Yes, but who are you?", False, 1500],
                        ["WHAT DIFFERENCE DOES THAT MAKE?", True, 1500],
                        ["You tell me! What are you doing in my house?", False, 1500],
                        ["I'VE EXPLAINED THIS THREE TIMES NOW.", True, 2000],
                        ["...", False, 1500],
                        ["KEITH IS-", True, 1000],
                        ["Gone, yes, I heard you the first time.", False, 1000],
                        ["THEN WHAT'S THE PROBLEM?", True, 1500],
                        ["For starters?", False, 1500],
                        ["I don't know any Keiths.", False, 1000],
                        ["I SUPPOSE NOT ANYMORE.", True, 1500],
                        ["...", False, 1500],
                        ["Look, I think maybe you have the wrong house.", False, 1000],
                        ["NO, I THINK NOT.", True, 2500],
                        ["YOURS IS THE ONLY HOUSE AROUND HERE WITH A TIME MACHINE.", True, 1500],
                        ["A what?", False, 2000],
                        ["A TIME MACHINE!", True, 1000],
                        ["THAT'S YOURS IN THE CORNER, ISN'T IT?", True, 1000],
                        ["Um...", False, 1500],
                        ["Well...", False, 1000],
                        ["You know, I suppose it is. Huh.", False, 1000],
                        ["EXACTLY! THAT MAKES YOU THE ONLY ONE WHO CAN GO BACK FOR KEITH.", True, 1500],
                        ["But why would I go back for Keith?", False, 3000],
                        [". . .", True, 1500],
                        ["DO WE REALLY NEED TO GO OVER THIS AGAIN?", True, 1000],
                        ["...", False, 1500],
                        ["If I use this time machine, will you leave me alone?", False, 1500],
                        ["IF YOU'D LIKE.", True, 2000],
                        ["BUT YOU'RE NOT GOING BACK FOR ME.", True, 1500],
                        ["YOU'RE GOING BACK FOR-", True, 1500],
                        ["Keith, I get it already!", False, 1500],
                        ["AS YOU SAY.", True, 1500],
                        ["Fine, whatever. I'll do it.", False, 1500],
                        ["I HOPE YOU FIND WHAT YOU'RE LOOKING FOR.", True, 1500],
                        ["...", False, 2500],
                        ["You better be gone by the time I get back.", False, 1000],
                        ["Now, how do I turn this thing-", False, 1500],
                        ["Aaagghhhhh!!!", False, 1500],
                        ["(YOU'VE SUCCESSFULLY USED YOUR TIME MACHINE! PRESS ANY KEY TO CONTINUE).", True, 2500]],
    "level1_cutscene" : [["Ooomph!", False, 0],
                         ["Ugh. That was a bumpier ride than I expected.", False, 1000],
                         ["Hey, what gives!", False, 2000],
                         ["This is just my backyard!", False, 1500],
                         ["And where'd my time machine go?!", False, 1500],
                         ["IT SEEMS TO HAVE BROKEN UP WHEN YOU LANDED.", True, 2000],
                         ["You again?", False, 2000],
                         ["I'M JUST HERE TO HELP YOU THROUGH THIS.", True, 1500],
                         ["Fine. You can start by pointing me in Keith's direction.", False, 1500],
                         ["KEITH IS GONE.", True, 2000],
                         ["Gee, I think you might have mentioned that already.", False, 1500],
                         ["THE SHARDS OF YOUR MACHINE ARE AROUND HERE SOMEWHERE, THOUGH.", True, 2000],
                         ["YOU MIGHT WANT TO START BY LOOKING FOR THOSE.", True, 2500],
                         ["You know what?", False, 2000],
                         ["This is dumb.", False, 1500],
                         ["ONE MORE THING BEFORE YOU SET OFF, THOUGH:", True, 1500],
                         ["THIS PLACE IS A LITTLE HAUNTED.", True, 2000],
                         ["...", False, 2000],
                         ["My backyard?", False, 1000],
                         ["TRY NOT TO LET YOUR SPIRITS GET YOU DOWN.", True, 1500],
                         ["I changed my mind.", False, 1500],
                         ["This is really, really dumb.", False, 1500],
                         ["GOOD LUCK, FRIEND.", True, 2000],
                         ["YOUR JOURNEY AWAITS.", True, 1000],
                         ["(PRESS ANY KEY TO CONTINUE).", True, 2500]],
    "level2_cutscene" : [["LEVEL TWO TEXT", True, 1500]],
    "level3_cutscene" : [["LEVEL THREE TEXT", True, 1500]],
    "level4_cutscene" : [["LEVEL FOUR TEXT", True, 1500]],
    "level5_cutscene" : [["LEVEL FIVE TEXT", True, 1500]]
}
